### ISSUE TITLE
Concepts>disk-aggregates-concepts redirects to cluster admin overivew page.

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/ontap#1026]
### Page URL

https://docs.netapp.com/us-en/ontap/concepts/aggregates-raid-groups-concept.html

### Page title

Local tiers (aggregates) and RAID groups

### Summary

This link: https://docs.netapp.com/us-en/ontap/concepts/disks-aggregates-concept.html seems to redirect to the following link: https://docs.netapp.com/us-en/ontap/disks-aggregates/index.html

Is this by design?  Seems to put reader in an place they were not expecting.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@tansley-netapp yes this is expected behavior.  When content is reorganized in a way that necessitates a change in url, we create redirects so that users with bookmarks don't experience unexpected broken links.

How did you come to the redirect? Did you have the url in questioned bookmarked?  Did the redirect not have the information you were seeking?

**Comment by netapp-aherbin** [comment]
Closing this issue.  Please feel free to reopen if needed.
