### ISSUE TITLE
TSSE efficient mode not automatically set?

### ISSUE THREAD

**Issue by jhubert-netapp** [NetAppDocs/ontap#1186]
### Page URL

https://docs.netapp.com/us-en/ontap/volumes/enable-temperature-sensitive-efficiency-concept.html

### Page title

Temperature-sensitive storage efficiency overview

### Summary

Needs clarification on non-TSSE platform definition - Efficient mode was not set on volumes migrated from a FAS9000 => C800 running Ontap 9.12.1P7.  But I believe was set to efficient for volumes migrated from an AFF to C800. 

Temperature-sensitive storage efficiency enabled on C-Series platforms
Temperature-sensitive storage efficiency is enabled by default on AFF C-Series platforms and when migrating volumes from a non-TSSE platform to a TSSE-enabled C-Series platform using volume move or SnapMirror with the following releases installed on the destination:

ONTAP 9.12.1P4 and later

ONTAP 9.13.1 and later

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
**Opening Jira to internally record related actions taken as a result of this issue:**  

Emailed Jeff:  The behavior is expected.  TSSE can only be enabled on thinly provision DP volumes.

Jeff's response:  The migrated volumes were not DP volumes.  I believe only volumes on the FAS with secondary compression enabled, once migrated to the C-series, do show TSSE enabled.
I don’t believe any volumes on the FAS had TSSE enabled.

**Below is email thread with ENG for further details**

From: Stroman, Amanda 
Sent: Thursday, December 7, 2023 2:53 PM
To: Ansley, Tony <Tony.Ansley@netapp.com>; Chuggani, Roopesh <Roopesh.Chuggani@netapp.com>; Tella, Venkateswarlu <Venku.Tella@netapp.com>; G, Mahalakshmi <Mahalakshmi.G@netapp.com>
Subject: RE: TSSE customer question

Thanks Tony!

[@G, Mahalakshmi](mailto:Mahalakshmi.G@netapp.com) our documentation states:  You can enable temperature-sensitive storage efficiency on existing AFF volumes and on thinly provisioned non-AFF DP volumes…. Temperature-sensitive storage efficiency is enabled by default on AFF C-Series platforms and when migrating volumes from a non-TSSE platform to a TSSE-enabled C-Series platform using volume move or SnapMirror …

Does non-AFF and non-TSSE mean FAS?

From: Ansley, Tony <[Tony.Ansley@netapp.com](mailto:Tony.Ansley@netapp.com)> 
Sent: Thursday, December 7, 2023 2:27 PM
To: Stroman, Amanda <[Amanda.Stroman@netapp.com](mailto:Amanda.Stroman@netapp.com)>; Chuggani, Roopesh <[Roopesh.Chuggani@netapp.com](mailto:Roopesh.Chuggani@netapp.com)>; Tella, Venkateswarlu <[Venku.Tella@netapp.com](mailto:Venku.Tella@netapp.com)>; G, Mahalakshmi <[Mahalakshmi.G@netapp.com](mailto:Mahalakshmi.G@netapp.com)>
Subject: RE: TSSE customer question

Amanda,

I have not taken provisioning type into consideration at all.  I am only trying to describe what happens to the replicated data based on what the volume’s compression type is at the time of the replication. If provisioning affects the SE before the relationship is created, then we would see that volume as that type of compression.

I am not familiar with the ONTAP processes for determining what type of SE should be applied based on provisioning.

Thanks,

Tony Ansley
ONTAP Technical Marketing Engineer
NetApp

Mobile: 512.565.8644
Email:  [tony.ansley@netapp.com](mailto:tony.ansley@netapp.com)

From: Stroman, Amanda <[Amanda.Stroman@netapp.com](mailto:Amanda.Stroman@netapp.com)> 
Sent: Thursday, December 7, 2023 12:45 PM
To: Ansley, Tony <[Tony.Ansley@netapp.com](mailto:Tony.Ansley@netapp.com)>; Chuggani, Roopesh <[Roopesh.Chuggani@netapp.com](mailto:Roopesh.Chuggani@netapp.com)>; Tella, Venkateswarlu <[Venku.Tella@netapp.com](mailto:Venku.Tella@netapp.com)>; G, Mahalakshmi <[Mahalakshmi.G@netapp.com](mailto:Mahalakshmi.G@netapp.com)>
Subject: RE: TSSE customer question

Thanks Tony,

Am I correctly interpreting this to mean that if a non-TSSE source volume is moved from a FAS to an AFF C-Series, TSSE is not automatically enabled on the source volume for existing data (regardless of whether the volume is thick or thin?  TSSE is automatically enabled for new data on the migrated volume if the volume is thin provisioned?

Amanda

From: Ansley, Tony <[Tony.Ansley@netapp.com](mailto:Tony.Ansley@netapp.com)> 
Sent: Wednesday, December 6, 2023 4:59 PM
To: Chuggani, Roopesh <[Roopesh.Chuggani@netapp.com](mailto:Roopesh.Chuggani@netapp.com)>; Tella, Venkateswarlu <[Venku.Tella@netapp.com](mailto:Venku.Tella@netapp.com)>; Stroman, Amanda <[Amanda.Stroman@netapp.com](mailto:Amanda.Stroman@netapp.com)>; G, Mahalakshmi <[Mahalakshmi.G@netapp.com](mailto:Mahalakshmi.G@netapp.com)>
Subject: RE: TSSE customer question

Here is a summary table that is available in the SnapMirror Technical Presentation on FieldPortal:

 

Thanks,

Tony Ansley
ONTAP Technical Marketing Engineer
NetApp

Mobile: 512.565.8644
Email:  [tony.ansley@netapp.com](mailto:tony.ansley@netapp.com)

From: Chuggani, Roopesh <[Roopesh.Chuggani@netapp.com](mailto:Roopesh.Chuggani@netapp.com)> 
Sent: Wednesday, December 6, 2023 10:07 AM
To: Tella, Venkateswarlu <[Venku.Tella@netapp.com](mailto:Venku.Tella@netapp.com)>; Stroman, Amanda <[Amanda.Stroman@netapp.com](mailto:Amanda.Stroman@netapp.com)>; G, Mahalakshmi <[Mahalakshmi.G@netapp.com](mailto:Mahalakshmi.G@netapp.com)>; Ansley, Tony <[Tony.Ansley@netapp.com](mailto:Tony.Ansley@netapp.com)>
Subject: Re: TSSE customer question

+ Tony,
he build a support matrix for Snapmirror behavior.
For replication cases  TSSE gets enabled by default only if volume is a no-se volume at source and thin provisioned.
For other cases TSSE has to be enabled manually either through CLI or System Manager.
If volume is thick provisioned that will first need to be converted to thin and then TSSE can be enabled on it.

-  Roopesh


From: Tella, Venkateswarlu <[Venku.Tella@netapp.com](mailto:Venku.Tella@netapp.com)>
Date: Wednesday, 6 December 2023 at 9:14 PM
To: Stroman, Amanda <[Amanda.Stroman@netapp.com](mailto:Amanda.Stroman@netapp.com)>, G, Mahalakshmi <[Mahalakshmi.G@netapp.com](mailto:Mahalakshmi.G@netapp.com)>
Cc: Chuggani, Roopesh <[Roopesh.Chuggani@netapp.com](mailto:Roopesh.Chuggani@netapp.com)>
Subject: RE: TSSE customer question
+ Roopesh for clarification on the release matrix as he worked on C-series support.
 
Reg FAS: The TSSE is not supported on FAS as of now for both thick and thin provision volumes
though in future we plan to support on FAS for thin provision voumes.
NOTE: The support is from the perspective of new volume and new data being generated on FAS
but the FAS can have TSSE volumes due to migration of vol-move or LRSE.
 
-Venku
 
From: Stroman, Amanda <[Amanda.Stroman@netapp.com](mailto:Amanda.Stroman@netapp.com)> 
Sent: Wednesday, December 6, 2023 1:31 AM
To: G, Mahalakshmi <[Mahalakshmi.G@netapp.com](mailto:Mahalakshmi.G@netapp.com)>; Tella, Venkateswarlu <[Venku.Tella@netapp.com](mailto:Venku.Tella@netapp.com)>
Subject: TSSE customer question
 
Hi Maha, Venkat,
 
We state the following in our documentation:
 
Temperature-sensitive storage efficiency is enabled by default on AFF C-Series platforms and when migrating volumes from a non-TSSE platform to a TSSE-enabled C-Series platform using volume move or SnapMirror with the following releases installed on the destination:
•	ONTAP 9.12.1P4 and later
•	ONTAP 9.13.1 and later
A customer moved volumes from a FAS9000 to a C800.  TSSE was not set on the moved volumes.  
 
Based on our documentation, TSSE is supported on FAS platforms for thinly provisioned DP volumes.  So, if the volumes moved from the FAS9000 were not thinly provisioned DP volumes, this would explain why TSEE was not enabled by default, correct?
 
Amanda Stroman

**Comment by netapp-aherbin** [comment]
Opened Jira 1540 to record internal emails.
