### ISSUE TITLE
missing information

### ISSUE THREAD

**Issue by YuliaNetA** [NetAppDocs/ontap#1241]
### Page URL

https://docs.netapp.com/us-en/ontap/upgrade/prepare.html

### Page title

Prepare for an ONTAP software upgrade

### Summary

![Screenshot 2024-02-01 144722](https://github.com/NetAppDocs/ontap/assets/139471932/f4ae9b56-8aaf-43ac-bfe4-22aeda879357)
Per google search there should be information about Quiesce SnapMirror DP operations before upgrading ONTAP but it is not bringing to desired page, istead it just open "Prepare for an ONTAP softwaRE UPGRADE" PAGE.  and this page cannot be found on doc NetApp page as well

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@YuliaNetA thank you for your inquiry.  The topic you found in google has been removed from our documentation set because it is not longer required to quiesce SnapMirror relationship before upgrade.  This is a very recent update.  If the topic is found or has been bookmarked it will auto redirect to the current necessary steps to prepare for ONTAP upgrade, so this is expected.

**Comment by netapp-joey** [comment]
Hello
"...it is not longer required to quiesce SnapMirror relationship before upgrade."

As far as I know nothing has changed with this best practice / requirement. What's the source of this?

**Comment by netapp-aherbin** [comment]
@netapp-joey can you ping me internally (aherbin) and I'll connect you with the ENG source on this.

**Comment by netapp-aherbin** [comment]
Closing the issue. ONTAPDOC-1585 and CONTAP-102397 references for change.
