### ISSUE TITLE
Add "can't modify read-only volumes" as a limitation, especially with respect to DP type volumes

### ISSUE THREAD

**Issue by tespinoz-netapp** [NetAppDocs/ontap#1341]
### Page URL

https://docs.netapp.com/us-en/ontap/smb-admin/limits-when-cli-set-file-folder-security-concept.html

### Page title

Limits when using the CLI to set file and folder security

### Summary

It makes sense to specify that read-only volumes (like DP-type volumes) can't have modifications applied to them, even via the ONTAP CLI, because they're in a read-only state.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@tespinoz-netapp thanks for your feedback. We feel that "read-only" is sufficient to indicate a volume can't be modified (assuming this is expected behavior). If there's some additional nuance for DP-specific volumes you think we need to add that could clarify this for customers, please let us know.
