### ISSUE TITLE
Correction in example of creation scanning pools

### ISSUE THREAD

**Issue by martenso** [NetAppDocs/ontap#1403]
### Page URL

https://docs.netapp.com/us-en/ontap/antivirus/create-scanner-pools-disaster-recovery-mcc-task.html

### Page title

Create scanner pools in MetroCluster configurations

### Summary

Hi Team,
from my understanding and interpretation of the picture the command example for creating primary and secondary pools in mcc configuration should be:

> cluster1::> vserver vscan scanner-pool create -vserver cifssvm1 -
> scanner-pool pool1_for_site1 -hostnames scan1 -privileged-users cifs
> \u1,cifs\u2
> 
> cluster1::> vserver vscan scanner-pool create -vserver cifssvm1 -
> scanner-pool pool1_for_site2 -hostnames **scan2** -privileged-users cifs
> \u1,cifs\u2
> 
> cluster1::> vserver vscan scanner-pool create -vserver cifssvm1 -
> scanner-pool pool2_for_site1 -hostnames scan2 -privileged-users cifs
> \u1,cifs\u2
> 
> cluster1::> vserver vscan scanner-pool create -vserver cifssvm1 -
> scanner-pool pool2_for_site2 -hostnames **scan1** -privileged-users cifs
> \u1,cifs\u2

If you would configure as actual documented then the primary pool of site 2 (pool1_for_site2) would be the same scanner host (scan1) for primary pool for site 1.

please correct me if I'm wrong.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mwallis** [comment]
Hi @martenso, thank you for bringing this to our attention - we'll work with engineering to make this part of the documentation clearer.

**Comment by netapp-mwallis** [comment]
Hi @martenso, the documentation examples in this section that deal with applying the scanner policy in MetroCluster configurations has been updated to produce the expected behavior.  This should resolve the issue - please reach out with any concerns.  The below link should have the changes, although it might take a day or so before the changes appear.  Thanks!

https://docs.netapp.com/us-en/ontap/antivirus/apply-scanner-policies-disaster-recovery-mcc-task.html
