### ISSUE TITLE
Compatibility about 9.9.0 and 9.10.0

### ISSUE THREAD

**Issue by imasafum** [NetAppDocs/ontap#301]
Page: [Compatible ONTAP versions for SnapMirror relationships](https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html)

To whom it may concern,

Regarding 9.9.0 and 9.10.0. these are only compatible with few ONTAP version in the Unified replication relationships table.（9.9.0 -> 9.9.0 or 9.9.1 / 9.10.0 -> 9.10.0 or 9.10.1）
Could you doublecheck this compatibility is correct? and if so, could you please teach me what the reason.
Best regards,

**Comment by netapp-forry** [comment]
Greetings,
Thanks for contacting us. My apologies for the delay in responding, we're just back in the office after the year-end shutdown.

As I read the table:
   9.9.0 interoperates with 9.5, 9.6, 9.7, 9.8, and 9.9.0
   9.10 0 interoperates with 9.5, 9.6, 9.7, 9.8, 9.9.0, 9.9.1, and 9.10.0

Do you think otherwise?

**Comment by netapp-forry** [comment]
Lenida, could you please follow up?

**Comment by netapp-lenida** [comment]
Hi Masafumi-san, I've sent you some information in a separate email, and I'm including some of it here. I'm also attaching a screenshot of the releases with which unified replication should interoperate. Please let me know if this helps. Thank you.
![image](https://user-images.githubusercontent.com/54081920/149002791-9a417c2d-f503-47c3-813e-f199f6d37329.png)

**Comment by netapp-lenida** [comment]
Followed up in a separate email. I believe this issue has been resolved.
