### ISSUE TITLE
9.9.0 and 9.10.0 are not CVO only releases

### ISSUE THREAD

**Issue by gadio** [NetAppDocs/ontap#348]
Page: [Compatible ONTAP versions for SnapMirror relationships](https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html)

Please note: 9.9.0 and 9.10.0 are versions that are also used not only by CVO but also by FSx-ONTAP and CVS/ANF.
This was also noted by AWS.

**Comment by gadio** [comment]
If you need to contact me, please look up my NetApp email (Gadi Oren). I'm the PM in charge of FSx and CVO.

**Comment by netapp-forry** [comment]
Thanks Gadi -- @netapp-lenida is following up.

**Comment by netapp-forry** [comment]
This issue is on hold pending resolution of FSx content strategy questions.
@netapp-ehoffman, @jenatnetapp - FYI

**Comment by netapp-forry** [comment]
Hi Gadi,
Per Jennifer and Ed, we have resolved the FSx question; we will not FSx feature support in the ONTAP library.
I believe the same is true for CVS/ANF feature support; CVS/ANF users should not have to consult the ONTAP library.
Please contact me directly if you think otherwise -- forry@netapp.com
Thanks for contacting us and helping us resolve these issues.
