### ISSUE TITLE
ssh-ed25519 keys not working in FIPS mode

### ISSUE THREAD

**Issue by florianmulatz** [NetAppDocs/ontap#443]
Page: [Configure network security using federal information processing standards (FIPS)](https://docs.netapp.com/us-en/ontap/networking/configure_network_security_using_federal_information_processing_standards_@fips@.html)

From my point of perspective is the documentation not correct. I tried to enable key-based authentication with an  ssh-ed25519 type key which was not working. With ecdsa-sha2-nistp256 it was working though.

Cheers

**Comment by netapp-forry** [comment]
Hello Florian -- thanks for letting us know. This is actually a known issue, we have a fix in the works. We'll let you know when it's live.

**Comment by netapp-forry** [comment]
Update -- we recently updated this content, it should be correct. I will report this to our Dev team and see what they say.

**Comment by netapp-forry** [comment]
One question, Florian: what ONTAP release are you running?
Thanks!

**Comment by florianmulatz** [comment]
Hi Mark, we're on NetApp Release 9.7P12: Tue Mar 02 23:38:44 UTC 2021.
Cheers

**Comment by netapp-forry** [comment]
Hello again -- I asked one of our SW engineers about this. He thinks that the documentation is correct as is, but he recommends that you check with NetApp Support about your particular configuration. I agree, because this is getting into an area beyond his expertise or mine.
So please contact NetApp Support about this issue. If it turns out that there's a problem with the documentation, Support will let us know.
Thanks again for contacting us.

**Comment by florianmulatz** [comment]
Thx for your time guys - I'll contact the support ont that.
