### ISSUE TITLE
FlashPool Reference In Wrong Spot

### ISSUE THREAD

**Issue by DrKeno** [NetAppDocs/ontap#496]
Page: [Considerations and requirements for using FabricPool](https://docs.netapp.com/us-en/ontap/fabricpool/requirements-concept.html)

This Flash Pool note that appears under the AFF platform bullet item should be moved to be under the FAS bullet item:
You cannot use Flash Pool aggregates (which contain both SSDs and HDDs).

Flash Pool aggregates are not possible on the AFF platform.  They apply to FAS platforms.

**Comment by netapp-ahibbard** [comment]
Thanks for letting us know -- we'll look into this ASAP.

**Comment by netapp-lenida** [comment]
@DrKeno, my apologies for taking so long to respond. It appears that the Flash Pool note you suggested should be moved out of the AFF section is actually saying that Flash Pool aggregates cannot be used on AFF plaforms, as you indicated, so it sounds like it is in the correct. The bullet says: 
"On AFF systems, you can use only all flash (all SSD) aggregates for FabricPool." The text that follows explains that Flash Pool aggregates cannot be used because they contain HDD and SSD, which is not supported on AFF. 

Closing this issue, but please feel free to contact us again if you still feel this is incorrect. Thanks!
