### ISSUE TITLE
Add explanation for "-"

### ISSUE THREAD

**Issue by zhihongluo** [NetAppDocs/ontap#556]
Page: [Compatible ONTAP versions for SnapMirror relationships](https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html)
![matrix](https://user-images.githubusercontent.com/104557809/176110373-1bb45ea4-b5dd-42d9-826d-ff7aa452bef5.png)

Hello Team

Would you please add more explanation for the symbol "-", like this means not suitable here, something like that, because some of customers would ask what's the mean for "-" in this table.

**Comment by netapp-forry** [comment]
Thanks Zhihong, that had occurred to me too. The problem I see is that half of the diagram would be filled with "n/a". I'm not sure that's a good user experience. Another option might be to grey out those cells, we can see whether our publishing system supports it. 
We're exploring some other presentation options, as well as some technical updates. When they're ready for review, would you be willing to comment?
Thanks again.

**Comment by zhihongluo** [comment]
Sure, looking forward to see the next update.


ZhiHong, Luo
Technical Support Escalation Engineer
Technical Support Center
Email: ***@***.******@***.***>

如需反馈我的服务水准，可联系我的经理Jeffrey Liu,  ***@***.******@***.***>

**Comment by netapp-lenida** [comment]
Hi Zhihong, I have updated the table in this topic to include n/a instead of "-", but this will probably be temporary since it does make that table very busy and not as easy to read. I have made some other changes as well that I hope will help make the information easier to understand. We are continuing to make improvements in the near future. In the meantime, I am closing this issue. Thanks again for bringing this to our attention.
