### ISSUE TITLE
ノードリストアのマニュアル改善を希望

### ISSUE THREAD

**Issue by yh152** [NetAppDocs/ontap#601]
Page: [構成バックアップファイルを使用してノード構成をリストアする](https://docs.netapp.com/ja-jp/ontap/system-admin/restore-node-config-backup-file-task.html)

 

・ノードリストアのマニュアル改善を希望
　　後述のKBには下記の項目の記載があるが、マニュアルにはないため、
　　ユーザーの誤操作、ご対応を防ぐためにも、docsのマニュアルの方にも、
　　当KBの内容を反映いただきたいです。
　　- HA構成の解除
　　- システムコンソールからの実施

・対象マニュアル
　<https://docs.netapp.com/ja-jp/ontap/system-admin/restore-node-config-backup-file-task.html>
・盛り込んでいただきたい手順の対象のKB
　<https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_restore_node_configuration>

**Comment by netapp-forry** [comment]
Translation from Outlook:
Page: [Restoring a node configuration using a configuration backup file](https://docs.netapp.com/ja-jp/ontap/system-admin/restore-node-config-backup-file-task.html)
- I would like to improve the manual of node restore
The following items are described in the KB described later, but it is not in the manual, so
In order to prevent user error operation and correspondence, the DOCS manual also has
I would like you to reflect the contents of this KB.
- Unlock HA configuration
- Implementation from the system console
・Target manual
　 https://docs.netapp.com/ja-jp/ontap/system-admin/restore-node-config-backup-file-task.html
・KB of the target of the
　 [procedure you would like to include https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_restore_node_configuration](https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_restore_node_configuration)

**Comment by netapp-forry** [comment]
Thank you for contacting us -- my apologies that we're not capable of an immediate response in Japanese. We are investigating your question and will respond as soon as possible.

**Comment by yh152** [comment]
Thank you for your response

 

This is Hamada.

 

I cannot recognize the performance graph after the day of 11. Sep. on AIQ., 

not only 451809000064, but also all users of NEC Corp. (Japan).

Would you please tell me how to fix this??

 

Thank you for your help in advance.

 



 

 

 

HAMADA, Yoshitaka

Alliance Account Manager

 

NEC

+81-80-1038-0701 Mobile Phone

***@***.***

 

        ＼Orchestrating a brighter world

     <http://jpn.nec.com/profile/solutionsforsociety/> http://jpn.nec.com/profile/solutionsforsociety/

 



 

------- Forwarded Message

**Comment by yh152** [comment]
This is Hamada.

I mis-posted  the wrong e-mail , so much sorry for this. Please ignore previous e-mail on AIQ.

Thank you for your cooperation.

 

 

 

 

 

HAMADA, Yoshitaka

Alliance Account Manager

 

NEC

+81-80-1038-0701 Mobile Phone

***@***.***

 

        ＼Orchestrating a brighter world

     <http://jpn.nec.com/profile/solutionsforsociety/> http://jpn.nec.com/profile/solutionsforsociety/

 



 

------- Forwarded Message

 

 

 

From: HAMADA YOSHITAKA(濱田　欣孝) 
Sent: Monday, October 3, 2022 2:26 PM
To: NetAppDocs/ontap ***@***.***>; NetAppDocs/ontap ***@***.***>
Cc: Author ***@***.***>; Kato, Chiaki ***@***.***>; Tanaka, Takayuki ***@***.***>
Subject: RE: [NetAppDocs/ontap] ノードリストアのマニュアル改善を希望 (Issue #601)

 

 

 

 

Thank you for your response

 

This is Hamada.

 

I cannot recognize the performance graph after the day of 11. Sep. on AIQ., 

not only 451809000064, but also all users of NEC Corp. (Japan).

Would you please tell me how to fix this??

 

Thank you for your help in advance.

 



 

 

 

HAMADA, Yoshitaka

Alliance Account Manager

 

NEC

+81-80-1038-0701 Mobile Phone

***@***.*** ***@***.***> 

 

        ＼Orchestrating a brighter world

     <http://jpn.nec.com/profile/solutionsforsociety/> http://jpn.nec.com/profile/solutionsforsociety/

 



 

------- Forwarded Message

**Comment by netapp-aherbin** [comment]
After discussion with the SMEs, it was determined that the content for the 2-node configuration should not be public facing.  The procedure is risky, and customers should only attempt it with assistance from support.  The KDE team will update the KB to move the content for 2-node configurations to internal access only and add a note for customers contact support if they need to restore a 2-node configuration.

The product documentation already includes the procedure for the single node.  We will keep this content and add a pointer to the KB for 2-node configurations.

**Comment by netapp-gudugunti** [comment]
@yh152 Hope your query is resolved per the last comment on 8 Nov. Please comment to keep it open for further review.
