### ISSUE TITLE
Confusion with commands

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/ontap#633]
Page: [Automatic giveback commands](https://docs.netapp.com/us-en/ontap/high-availability/ha_automatic_giveback_commands.html)

Hi,

couple of feedback here.

Issue 1:
we could see there is a reference of a parameter name -onfailure. I guess it is a typo as we dont see that option referenced in any of the tables. If it is correct then -onfailure needs a explanation here.

Issue 2:
we could see "The -auto-giveback parameter controls giveback after panic and all other automatic takovers.". However in the immediate next paragraph we see the below, that contradicts since -onreboot supercedes it.
 "The -onreboot parameter applies to reboots and halt commands issued from ONTAP. When the -onreboot parameter is set to false, a takeover does not occur in the case of a node reboot. Therefore, automatic giveback cannot occur, regardless of whether the -auto-giveback parameter is set to true. A client disruption occurs."

Issue 3:
   
The **-auto-giveback parameter controls giveback after panic** and all other automatic takovers. If the -onreboot parameter is set to true and a takeover occurs due to a reboot, then automatic giveback is always performed, regardless of whether the -auto-giveback parameter is set to true.

I guess thats again a issue.it should be -auto-giveback-panic parameter that controls giveback after panic and not -auto-giveback.

**Comment by netapp-forry** [comment]
Thanks for letting us know -- we'll address this issue ASAP.

**Comment by netapp-aherbin** [comment]
I'm just following up to let you know we are actively working clarifying this content and will provide and update as soon as possible.

**Comment by netapp-aherbin** [comment]
Issue 1:  We have added explanation of the -onfailure parameter along with a link to the ONTAP manual pages for this and all other the storage failover modify command parameters.

Issue 2:  Instead of trying to explain the table, which has added more confusion, we've removed this, verified the table content and allowed it to stand on its own.

Issue 3: Correct.  -auto-giveback-after-panic controls giveback after panic.  Again, we've verified the table combinations of the -onpanic, -auto-giveback, and -auto-giveback-after panic for accuracy and removed the ambiguous or conflicting statements.

Thank you for you feedback and let us know if there are any other issues we can address
