### ISSUE TITLE
wrong license link

### ISSUE THREAD

**Issue by merdos** [NetAppDocs/ontap#643]
Page: [Back up data to the cloud using SnapMirror](https://docs.netapp.com/us-en/ontap/task_dp_back_up_to_cloud.html)

the link provided on this page leads to a page that has old information. (an ng to request licenses, wich I am sure is not the case any longer)

**Comment by netapp-forry** [comment]
Thanks for letting us know, Mark -- we'll look into this ASAP.

**Comment by netapp-lenida** [comment]
Thanks, Mark. I've reached out to the licensing product manager to find the correct link. I'll update the information ASAP.

**Comment by netapp-lenida** [comment]
Thanks again for your feedback, Mark. I contacted the product manager and learned that the link is correct, but that he needs to request an update the text on that page. I worked with him to update the information in the topic you've reference, and he will be contacting the Support Site team to have the text on that linked page modified with something similar to what I've added. Closing this issue since our documentation is correct.
