### ISSUE TITLE
What happens when you set tiering policy to none

### ISSUE THREAD

**Issue by roscocheeta** [NetAppDocs/ontap#832]
Page: [About FabricPool tiering policies](https://docs.netapp.com/us-en/ontap/fabricpool/tiering-policies-concept.html)

Under the section "What happens when you modify the tiering policy of a volume in FabricPool" can we please add a section that explains what happens when you set the tiering policy to none

**Comment by netapp-lenida** [comment]
Thanks for the suggestion @roscocheeta. I'll look into this as soon as possible.

**Comment by netapp-lenida** [comment]
I haven't heard back from my Engineering contact on this. If you haven't already looked at the following topic, it might contain the information you're asking about:
https://docs.netapp.com/us-en/ontap/fabricpool/tiering-policies-concept.html#types-of-fabricpool-tiering-policies

**Comment by netapp-lenida** [comment]
I've added some details to the description of the "none" tiering policy. Here's the current text:

"The none tiering policy keeps a volume’s data in the performance tier and does not move cold to the cloud tier.

Setting the tiering policy to none prevents new tiering. Volume data that has previously been moved to the cloud tier remains in the cloud tier until it becomes hot and is automatically moved back to the local tier.

The tiering minimum cooling period does not apply because the data never moves to the cloud tier, and you cannot modify the setting.

When cold blocks in a volume with a tiering policy set to none are read, they are made hot and written to the local tier."

Closing this issue.
