### ISSUE TITLE
Pictures in the guide would be nice since most of it are actions in the ONTAP System Manager GUI.

### ISSUE THREAD

**Issue by davidhalldor** [NetAppDocs/ontap#84]
https://docs.netapp.com/us-en/ontap/index.html

**Comment by netapp-aherbin** [comment]
Hi David,  Thank you for feedback.  We are working to incorporate workflow diagrams and videos into our content.  We tend not to use screenshots if instructions can be clearly provided with text.  Are there specific topics you feel a workflow diagram or video would be especially helpful?

**Comment by davidhalldor** [comment]
Hi Aherbin,
Sequence diagrams would probably be the best to describe the user interactions with numbered step by step instructions for the user interaction in the UI.

**Comment by netapp-forry** [comment]
David, apologies for the very slow response.
I'm marking this "wont fix" for now because we're in the midst a massive library reorganization involving System Manager content. During the migration period, we are not planning to add new illustrations. However, when the migration is complete, we'll consider enhancements, including new or revised diagrams.
Thanks for your interest in NetApp documentation!
