### ISSUE TITLE
Please add ONTAP 9.12.1

### ISSUE THREAD

**Issue by chjones45** [NetAppDocs/ontap#855]
Page: [Compatible ONTAP versions for SnapMirror relationships](https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html)

Are you able to add 9.12.1 to these lists please? The one I am particularly interested in is the SnapMirror DR Relationships.

Thanks.

**Comment by netapp-lenida** [comment]
@chjones45 thanks for contacting us. SnapMirror XDP replaced SnapMirror DR in ONTAP 9.3, and SnapMirror DR was deprecated beginning with ONTAP 9.12.1. That's why the table only goes up to ONTAP 9.11.1, as described in the note above the SnapMirror DR table:

DP-type mirrors cannot be initialized beginning with ONTAP 9.11.1 and are completely deprecated in ONTAP 9.12.1. For more information, see [Deprecation of data protection SnapMirror relationships](https://mysupport.netapp.com/info/communications/ECMLP2880221.html)

I hopes this helps.

**Comment by chjones45** [comment]
Apologies, I didn't notice that. Thank you.

I find the Unified Relationships table hard to understand then. Does that same table hold true for SVM-DR XDP relationships? That SnapMirror DP table was very easy to understand.
