### ISSUE TITLE
Need update for DS460C drawer auto assign policy

### ISSUE THREAD

**Issue by jhubert-netapp** [NetAppDocs/ontap#923]
Page: [Change settings for automatic assignment of disk ownership](https://docs.netapp.com/us-en/ontap/disks-aggregates/configure-auto-assignment-disk-ownership-task.html)

There is no public documentation on DS460C drawer auto assignment, which seems to vary by Ontap release, and is inconsistent with Boot Menu option #9b/#9c. Please update documentation to include drawer auto assignment policy.

**Comment by netapp-aherbin** [comment]
Moved to Jira (ONTAPDOC-1050) for internal discussion and new content development.

**Comment by netapp-lisa** [comment]
Hi Jeff, I've been assigned to your request. I just want to verify I understand what you are asking for. You're saying that when a user replaces a failed DS460C drawer, they need to understand the autoassignment policy for the drives in the drawer (especially since it seems to vary per ONTAP release), correct? You are also saying that the Boot Menu option #9b/#9c doesn't reflect the differences per ONTAP releases?

**Comment by netapp-lisa** [comment]
Hi Jeff, I'm working on your request. I just want to verify I understand what you are asking for. You're saying that when a user replaces a failed DS460C drawer, they need to understand the autoassignment policy for the drives in the drawer (especially since it seems to vary per ONTAP release), correct? You are also saying that the Boot Menu option #9b/#9c doesn't reflect the differences per ONTAP releases?

**Comment by netapp-aherbin** [comment]
Closing Issue.  Tracking via internal issue (ONTAPDOC 1050).
